remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins: 
  - jekyll-remote-theme 
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  
title: Damian Skowroński
description: Data Science student at WUT

url: https://skowronskid.github.io
  
colot-scheme: dark
email: skowronskid@outlook.com


platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/skowronskid
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: www.linkedin.com/in/skowronski-damian
    
    
# navigation:
#   - name: Home Page
#     link: ./
#     sublist:
#       - name: Usage
#         link: ./#usage
#       - name: Customizing
#         link: ./#customizing
#       - name: Customizing Sidebar
#         link: ./#customizing-sidebar
#       - name: Navigation
#         link: ./#navigation
#       - name: Example
#         link: ./#example
#       - name: Stylesheet
#         link: ./#stylesheet
#       - name: Credits
#         link: ./#credits
#   - name: Sample
#     link: ./another-page.html
#     sublist:
#       - name: Image
#         link: ./another-page.html#small-image

