remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins: 
  - jekyll-remote-theme 
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  
title: Damian Skowroński
description: Data Science student at WUT



colot-scheme: dark
email: skowronskid@outlook.com


platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/skowronskid
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/skowronski-damian/
    
    
navigation:

    - name: Python
      link: ./#python
    - name: R
      link: ./#r
    - name: Matlab
      link: ./#matlab
    - name: Java
      link: ./#java
